In [19]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np

In [20]:
rng = np.random.default_rng(42)
n = 200

In [21]:
cats = rng.multivariate_normal(mean = [-1.0 , -1.0] , cov = [[1.0 , 0.3] , [0.3 , 1.0]] , size = n)
cats[:10]
len(cats)

dogs = rng.multivariate_normal(mean = [1.2 , 1.0] , cov = [[1.0 , -0.2] , [-0.2 , 1.0]] , size = n)
dogs[:10]
len(dogs)

array([[-0.63040787, -1.86093366],
       [-2.16147869, -1.04858751],
       [ 1.34335464, -0.19740493],
       [-0.91597659, -1.29015987],
       [-0.48178688, -1.49112207],
       [-2.16914123, -1.2488454 ],
       [-1.72012054, -0.38635076],
       [-0.8685538 , -1.88528236],
       [-0.73001379, -1.86457898],
       [-1.67869271, -1.73776584]])

200

array([[ 1.46357853,  0.98532573],
       [ 0.31539759,  1.38655484],
       [ 0.62817437,  1.23556321],
       [ 1.81568168,  1.43358614],
       [ 1.92385683, -1.36377902],
       [ 0.87218745, -1.6240043 ],
       [ 2.19936499,  0.94860224],
       [ 1.54576368,  0.90442318],
       [ 1.19599819,  2.68340668],
       [ 2.1096369 ,  1.80252887]])

200

In [22]:
X = np.vstack([cats , dogs])
X[:10]
X.shape

y = np.hstack([np.zeros(n) , np.ones(n)])
y[:10]
y.shape

array([[-0.63040787, -1.86093366],
       [-2.16147869, -1.04858751],
       [ 1.34335464, -0.19740493],
       [-0.91597659, -1.29015987],
       [-0.48178688, -1.49112207],
       [-2.16914123, -1.2488454 ],
       [-1.72012054, -0.38635076],
       [-0.8685538 , -1.88528236],
       [-0.73001379, -1.86457898],
       [-1.67869271, -1.73776584]])

(400, 2)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

(400,)

In [23]:
print("X shape:" , X.shape , "| y mean (class balance):" , y.mean())
print("First 3 rows of X:\n" , X[:3])

X shape: (400, 2) | y mean (class balance): 0.5
First 3 rows of X:
 [[-0.63040787 -1.86093366]
 [-2.16147869 -1.04858751]
 [ 1.34335464 -0.19740493]]
